OENIK_PROG4_2021_1_I0DL0D/Web/Models/Student.cs
// <copyright file="Student.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace DrivingSchool.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Student table.
    /// </summary>
    public class Student
    {
        /// <summary>
        /// Gets or sets Id of student.
        /// </summary>
        [Display(Name = "Student Id")]
        public int StudentId { get; set; }

        /// <summary>
        /// Gets or sets FirstName of student.
        /// </summary>
        [Display(Name = "Student First Name")]
        [Required]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets LastName of student.
        /// </summary>
        [Display(Name = "Student Last Name")]
        [Required]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets DateOfBirth of student.
        /// </summary>
        [Display(Name = "Student Date of Brith")]
        [Required]
        public DateTime DateOfBirth { get; set; }

        /// <summary>
        /// Gets or sets Sex of student.
        /// </summary>
        [Display(Name = "Student Sex")]
        [Required]
        public string Sex { get; set; }

        /// <summary>
        /// Gets or sets Email of student.
        /// </summary>
        [Display(Name = "Student Email")]
        [Required]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets PhoneNumber of student.
        /// </summary>
        [Display(Name = "Student Phone Number")]
        [Required]
        public string PhoneNumber { get; set; }
    }
}

OENIK_PROG4_2021_1_I0DL0D/Web/Models/StudentListViewModel.cs
// <copyright file="StudentListViewModel.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace DrivingSchool.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Student ViewModel.
    /// </summary>
    public class StudentListViewModel
    {
        /// <summary>
        /// Gets or sets StudentList.
        /// </summary>
        public List<Student> StudentList { get; set; }

        /// <summary>
        /// Gets or sets a student to edit.
        /// </summary>
        public Student EditedStudent { get; set; }
    }
}

OENIK_PROG4_2021_1_I0DL0D/Web/Controllers/StudentController.cs
// <copyright file="StudentController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace DrivingSchool.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using DrivingSchool.Logic;
    using DrivingSchool.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// Controller for students.
    /// </summary>
    public class StudentController : Controller
    {
        private IStudentsDrivingLogic logic;
        private IMapper mapper;
        private StudentListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="StudentController"/> class.
        /// </summary>
        /// <param name="logic">Student logic.</param>
        /// <param name="mapper">Automapper for conversion.</param>
        public StudentController(IStudentsDrivingLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.vm = new StudentListViewModel();
            this.vm.EditedStudent = new Models.Student();

            var students = logic.GetAllStudents();
            this.vm.StudentList = mapper.Map<IList<Data.Model.Student>, List<Models.Student>>(students);
        }

        /// <summary>
        /// Index action.
        /// </summary>
        /// <returns>Index page.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("StudentIndex", this.vm);
        }

        /// <summary>
        /// Details action.
        /// </summary>
        /// <param name="id">Id of student.</param>
        /// <returns>Details of one student.</returns>
        public IActionResult Details(int id)
        {
            return this.View("StudentDetails", this.GetStudentModel(id));
        }

        /// <summary>
        /// Remove action.
        /// </summary>
        /// <param name="id">Id of student.</param>
        /// <returns>Index page.</returns>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete Failed!";
            try
            {
                this.logic.RemoveStudent(id);
                this.TempData["editResult"] = "Delete Completed!";
            }
            catch (ArgumentException ex)
            {
                this.TempData["editResult"] = "Delete Failed! " + ex.Message;
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Edit action.
        /// </summary>
        /// <param name="id">Id of student.</param>
        /// <returns>Index page.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedStudent = this.GetStudentModel(id);
            return this.View("StudentIndex", this.vm);
        }

        /// <summary>
        /// Edit action.
        /// </summary>
        /// <param name="student">One student.</param>
        /// <param name="editAction">Action type.</param>
        /// <returns>Index page.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Student student, string editAction)
        {
            if (this.ModelState.IsValid && student != null)
            {
                this.TempData["editResult"] = "Edit Ok!";
                if (editAction == "AddNew")
                {
                    try
                    {
                        var localFormat = "M/d/yyyy";
                        string sh = student.DateOfBirth.ToString(localFormat);
                        this.logic.AddStudent(student.FirstName, student.LastName, sh, student.Email, student.PhoneNumber, student.Sex);
                        this.TempData["editResult"] = "Add Completed!";
                    }
                    catch (ArgumentException ex)
                    {
                        this.TempData["editResult"] = "Add Failed!" + ex.Message;
                    }
                }
                else
                {
                    try
                    {
                        this.logic.ChangeEmail(student.StudentId, student.Email);
                        this.logic.ChangeFirstName(student.StudentId, student.FirstName);
                        this.logic.ChangeLastName(student.StudentId, student.LastName);
                        this.logic.ChangePhoneNumber(student.StudentId, student.PhoneNumber);
                        this.logic.ChangeSex(student.StudentId, student.Sex);
                        this.logic.ChangeDOB(student.StudentId, student.DateOfBirth.ToString("M/d/yyyy"));
                        this.TempData["editResult"] = "Edit Completed!";
                    }
                    catch (ArgumentException ex)
                    {
                        this.TempData["editResult"] = "Edit Failed! " + ex.Message;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedStudent = student;
                return this.View("StudentIndex", this.vm);
            }
        }

        private Models.Student GetStudentModel(int id)
        {
            Data.Model.Student oneStudent = this.logic.GetStudentId(id);
            return this.mapper.Map<Data.Model.Student, Models.Student>(oneStudent);
        }
    }
}

OENIK_PROG4_2021_1_I0DL0D/Web/Views/Student/StudentDetails.cshtml
@model DrivingSchool.Web.Models.Student

@{
    ViewData["Title"] = "StudentDetails";
}

<h2>Datasheet of one student</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.StudentId)</td>
        <td>@Html.DisplayFor(m => m.StudentId)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.FirstName)</td>
        <td>@Html.DisplayFor(m => m.FirstName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.LastName)</td>
        <td>@Html.DisplayFor(m => m.LastName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.DateOfBirth)</td>
        <td>@Html.DisplayFor(m => m.DateOfBirth)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Sex)</td>
        <td>@Html.DisplayFor(m => m.Sex)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Email)</td>
        <td>@Html.DisplayFor(m => m.Email)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.PhoneNumber)</td>
        <td>@Html.DisplayFor(m => m.PhoneNumber)</td>
    </tr>
</table>

OENIK_PROG4_2021_1_I0DL0D/Web/Views/Student/StudentEdit.cshtml
@model DrivingSchool.Web.Models.Student

<h2>Student Edit</h2>

@using (Html.BeginForm("Edit", "Student"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.StudentId)

    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.FirstName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.FirstName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.LastName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.LastName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.DateOfBirth)</div>
    <div class="editor-field">@Html.EditorFor(m => m.DateOfBirth)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Sex)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Sex)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Email)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Email)</div>

    <div class="editor-label">@Html.LabelFor(m => m.PhoneNumber)</div>
    <div class="editor-field">@Html.EditorFor(m => m.PhoneNumber)</div>

    <input type="submit" value="SEND" />
}

OENIK_PROG4_2021_1_I0DL0D/Web/Views/Student/StudentIndex.cshtml
@model DrivingSchool.Web.Models.StudentListViewModel

@{
    ViewData["Title"] = "StudentIndex";
}

<h2>Student Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("StudentEdit", Model.EditedStudent)

@await Html.PartialAsync("StudentList", Model.StudentList)

OENIK_PROG4_2021_1_I0DL0D/Web/Views/Student/StudentList.cshtml
@model IEnumerable<DrivingSchool.Web.Models.Student>

<h2>Student List</h2>

@if (Model.Count() == 0)
{
                <p>No data in the database</p>
}
else
{
                <table border="1">
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.First().FirstName)</th>
                        <th>@Html.DisplayNameFor(m => m.First().LastName)</th>
                        <th>Datasheet</th>
                        <th>Delete</th>
                        <th>Modify</th>
                    </tr>
                    @foreach (var stud in Model)
                    {
                <tr>
                    <td>@Html.DisplayFor(m => stud.FirstName)</td>
                    <td>@Html.DisplayFor(m => stud.LastName)</td>
                    <td>@Html.ActionLink("{SHOW}", "Details", new { id = stud.StudentId }) </td>
                    <td>@Html.ActionLink("{DEL}", "Remove", new { id = stud.StudentId }) </td>
                    <td>@Html.ActionLink("{EDIT}", "Edit", new { id = stud.StudentId })</td>
                </tr>
                    }
                </table>
}